<?php
class weather
{
    public static function show()
    {
        $today = [
            "tep"=>30,
            "wind"=>7,
            "sun"=>"sunny",
        ];
        return serialize( $today );
    }
}


class  adapterWeather extends weather {
    public static function show()
    {
        $today = parent::show(); // TODO: Change the autogenerated stub
        $today = unserialize($today);
        return json_encode($today);
    }
}
$today = weather::show();
$todayWeather = unserialize($today);
print_r($todayWeather);


//java 代码也要获取天气了，但是，不认识serialize
//所以，需要使用适配器



$today = adapterWeather::show();
$today = json_decode($today, true);
print_r($today);