<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-5-25
 * Time: 14:40
 */

namespace DesignPattern\Structural\Adapter\ChinaWeather;


use DesignPattern\Structural\Adapter\HeWeather\HeWeather;

/**
 * 类适配器
 * Class HeWeatherClassAdapter
 * @package DesignPattern\Structural\Adapter\ChinaWeather
 */
class HeWeatherClassAdapter extends HeWeather implements WeaherInterface
{
    public function getForecastInfo($siteCode = '', $scope)
    {
        // TODO: Implement getForecastInfo() method.
        $heForecastInfo = $this->getForecast($siteCode);
        //经过一系列的数据处理，获得 $scope 的数据
        $heForecastInfo = "scope==>".$heForecastInfo;
        return $heForecastInfo;
    }

    public function getAir($siteCode = '')
    {
        // TODO: Implement getAir() method.
        return $this->getAirInfo( $siteCode );

    }

    public function humidity($siteCode = '')
    {
        return parent::humidity($siteCode); // TODO: Change the autogenerated stub
    }
}